CREATE DATABASE IF NOT EXISTS devsbook CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE devsbook;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    birthdate DATE NOT NULL,
    city VARCHAR(100),
    work VARCHAR(100),
    avatar VARCHAR(100),
    cover VARCHAR(100),
    token VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_relations (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_from INTEGER NOT NULL,
    user_to INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS posts_type (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_user INTEGER NOT NULL,
    id_type INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    body TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts_comments (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_post INTEGER NOT NULL,
    id_user INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    body TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts_likes (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_post INTEGER NOT NULL,
    id_user INTEGER NOT NULL,
    created_at DATETIME NOT NULL
);